# Generated by Django 5.2.6 on 2025-09-13 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Color, Size, Material', max_length=100, unique=True, verbose_name='Attribute Name')),
            ],
            options={
                'verbose_name': 'Attribute',
                'verbose_name_plural': 'Attributes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the brand.', max_length=255, unique=True, verbose_name='Name')),
                ('logo', models.ImageField(blank=True, help_text="The brand's logo image.", null=True, upload_to='brand', verbose_name='Logo')),
                ('website_url', models.URLField(blank=True, help_text='The official website of the brand.', verbose_name='Website URL')),
                ('description', models.TextField(blank=True, help_text='A brief description of the brand.', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the category.', max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(help_text='A unique, URL-friendly version of the name.', max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, help_text='A short description of the category.', verbose_name='Description')),
                ('parent', models.ForeignKey(blank=True, help_text='Assign a parent to create a category hierarchy.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalogue.category', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('sku', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='SKU (Stock Keeping Unit)')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('short_description', models.TextField(blank=True, help_text='A brief summary of the product.', verbose_name='Short Description')),
                ('is_published', models.BooleanField(default=False, help_text='Check this to make the product visible on the site.', verbose_name='Is Published')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalogue.brand', verbose_name='Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalogue.category', verbose_name='Category')),
                ('collections', models.ManyToManyField(blank=True, related_name='products', to='catalogue.collection', verbose_name='Collections')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='The specific value for the attribute (e.g., Red, Large).', max_length=255, verbose_name='Value')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.attribute', verbose_name='Attribute')),
                ('product', models.ManyToManyField(blank=True, related_name='attributes', to='catalogue.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Attribute',
                'verbose_name_plural': 'Product Attributes',
                'ordering': ['attribute__name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='The product image file.', upload_to='product', verbose_name='Image')),
                ('alt_text', models.CharField(help_text='Descriptive text for SEO and accessibility.', max_length=255, verbose_name='Alt Text')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Caption')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='The order in which to display images (0 comes first).', verbose_name='Display Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalogue.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['display_order'],
            },
        ),
    ]
